### ISSUE TITLE
Asset paths digests

### ISSUE THREAD

**Issue by saratovsource** [route/errgent#7]
Do not generates digests for asset paths

`<link rel="stylesheet" media="all" href="/assets/application.css">`
instead
`<link rel="stylesheet" media="all" href="/assets/application-9a249aeeaa09274a1980dd021fa84fd09d2e5d03e110b45f320737bafe17622d.css">`

**Comment by saratovsource** [comment]
Important:
Run rake tasks **separately**!
Example:

`$> bundle exec rake assets:precompile errgent`
don`t add digests (manifest **not loaded** yet!)

`$> bundle exec rake assets:precompile && bundle exec rake errgent`
add digests (manifest **reloaded**!)

Can you please add this remark to README? \cc @route

**Comment by route** [comment]
Long time no see, is this still useful thing to add to readme?)
